### ISSUE TITLE
Real sources

### ISSUE THREAD

**Issue by davelab6** [edwardtufte/et-bembo#1]
The source files in the repo today are apparently PFB files, old PostScript Type1 binary fonts. 

Is a .fog or .vfb file available (the native source file for Fontographer and Fontlab)

**Comment by godbyk** [comment]
In addition, the purported source files in the `source/1-suit/` directory are empty files (0 bytes).

**Comment by adamschwartz** [comment]
Thanks for letting me know. I’m not sure what’s going on here. There appears to be some issue with GitHub when committing these. I absolutely have the original files and will figure out a better way to post them. More to come.

**Comment by adamschwartz** [comment]
Try downloading and unzipping https://github.com/edwardtufte/et-bembo/blob/gh-pages/source/1-suit/originals.zip. Then see if you can make a PR back to https://github.com/edwardtufte/et-bembo with those files and we’ll see if they’re `0 bytes` in the PR.

**Comment by godbyk** [comment]
@adamschwartz The zip file contains 0-byte files except for the resource forks located in the `__MACOSX` directory. The actual font source files in the zip file are still 0 bytes, however.

**Comment by adamschwartz** [comment]
That’s odd because the zip file is 539 KB according to GitHub (https://github.com/edwardtufte/et-bembo/blob/gh-pages/source/1-suit/originals.zip) and when I unzip that on my machine I see this:

<img width="918" alt="screen shot 2015-09-20 at 3 40 27 pm" src="https://cloud.githubusercontent.com/assets/154613/9982537/f596025a-5fad-11e5-8e41-3c91b2ee2cad.png">
<img width="918" alt="screen shot 2015-09-20 at 3 40 29 pm" src="https://cloud.githubusercontent.com/assets/154613/9982539/f59a0af8-5fad-11e5-8d35-edbac246e3d1.png">
<img width="918" alt="screen shot 2015-09-20 at 3 40 31 pm" src="https://cloud.githubusercontent.com/assets/154613/9982538/f598a1d6-5fad-11e5-941d-1b80161e36e8.png">
<img width="918" alt="screen shot 2015-09-20 at 3 40 33 pm" src="https://cloud.githubusercontent.com/assets/154613/9982540/f5a0fac0-5fad-11e5-80b5-7313b5da2ebd.png">

_etc..._

**Comment by godbyk** [comment]
When I download the zip file, it's the same size for me. But all that space is consumed by the `__MACOSX` files and none of it by the original files.

Could you try zipping them up from the terminal?

```
$ cd /path/to/originals
$ tar -czvf originals.tgz *
```

Then upload the `originals.tgz` file.

**Comment by davelab6** [comment]
Zipping that way will not help; you need to convert them from resource-fork
using 'mac style' fonts to 'dos style' fonts.

**Comment by godbyk** [comment]
@davelab6 Ah, thanks for the input. I have no idea how fonts are managed on a Mac. I didn't realize that there were two different styles like that!

**Comment by adamschwartz** [comment]
Sounds like we’re all good. I’ll keep looking into how to get these in there such that the `zip` isn’t necessary, but for the time being I’ll close this ticket. Thanks @davelab6 and @godbyk.

**Comment by davelab6** [comment]
https://fontforge.github.io/macformats.html

**Comment by adamschwartz** [comment]
Thanks @davelab6

**Comment by ljrk0** [comment]
There are multiple hurdles here,

1. The files not being stored "as-is" but as Resource Forks
2. The Resource Forks are Apple Double encoded
3. The files are still Apple-specific Suitcase bitmap files or Postscript files in a slightly different, Apple-specific, format.

To access the original sources on a non macOS system, this is what I did:

1. Install the Perl module [Mac::AppleSingleDouble](https://metacpan.org/pod/Mac::AppleSingleDouble)
2. Install [fondu](http://fondu.sourceforge.net/)

After unzipping, I  use the first tool to convert all the Apple Double files like `._ETBook-BoldLF.suit` (Suitcase font for bitmap) or `._ETBookBolLF` (Postscript Outline) to Resource Fork files which have the same name but with`.rsrc` attached. Script from [this SuperUser answer](https://superuser.com/a/114301/369027):

```
$ unzip originals.zip
$ cd originals
$ rm -f *
$ find ../__MACOSX/originals -type f -not -name '*.rsrc' -exec perl -MMac::AppleSingleDouble -e 'for(@ARGV) {
    $a = new Mac::AppleSingleDouble($_);
    if(open $f, ">", $_.".rsrc") {
        binmode $f;
        print $f $a->get_entry(2);
        close $f;
    }
}' {} \;
```

The Suitcase Resource Forks (*.suit.rsrc) contain `FOND` (fond family information) as well as `NFNT` (bitmap font) resources which will be extracted and converted into `.bdf` and `.afm` files.

The Postscript Resource Forks (no *.suit*) contain `POST` (Postscript font) information which is simply dumped into a `.pfb` outline font.

```
$ find ../__MACOSX/originals -type f -name '*.rsrc' -exec fondu -afm {} \;     
```

Now, the originals directory contains both, the Bitmap and font metrics, as well as the PostScript Type 1 fonts.  We can actually even compare the checksum of the `.pfb`s extracted this way and the ones uploaded on GitHub, and we will find that they are the same to the last bit (given we don't have any hash collisions :D)

These are the "new" files:
[originals2.zip](https://github.com/edwardtufte/et-book/files/5591223/originals2.zip)
