### ISSUE TITLE
Trademark?

### ISSUE THREAD

**Issue by ghost** [edwardtufte/et-bembo#4]
Just checking but...you have sought legal advice about releasing a font named Bembo, I hope?

IANAL, but a quick search says that Bembo has been a registered trademark of Monotype in the US since 1985 for purposes of 'Typefaces, Typefonts, and Type Designs of Alphanumeric Characters and/or Typographical Symbols Recorded as Latent Images in Data Storage' and 1990 in the UK for similar. From the history on Wikipedia, it looks like Monotype chose the name of Bembo for their font in the 20s and no other font has ever had the name, so it's not a 'generic' like Garamond or Caslon.

**Comment by dpk** [comment]
As long as it’s called ‘ET Bembo’ I don’t _think_ there’s too much of an issue. See [this post by Joel Spolsky on one of his company’s products](http://www.joelonsoftware.com/articles/AardvarkMidtermReport.html) (heading ‘The Name’).

However: I am not a lawyer, this is not legal advice, etc. I would certainly advise the team here to double-check with a lawyer.
